fix(deps): Avoid packaging of jackson-module-scala*.jar in distributions
The presence of jackson-module-scala*.jar can cause a NoClassDefFoundError when present in the classpath before org.camunda.feel:feel-engine:scala-shaded. The dependency is excluded.

Added a verification step in module distro/run/assembly to assure that the library is not packaged.

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>