fix(tests): Revert refactoring lambda -> method reference
This reverts the change from #2a00dccd, because it broke the build with NoClassDefFoundError

fixes #1362